Repository nimblehq/flutter-ic-lydia-ryan, pull requests merged in 2023-07, with the labels that each got.

#83 [#31][#32] [UI] Star Emoji answer
  lib/model/ui/answer_ui_model.dart
  lib/resources/dimensions.dart
  lib/screens/surveydetails/widget/answer_rating_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
Labels: type : feature, @0.7.0

#87 [#86] Fix condition to show icon
  lib/screens/surveydetails/widget/question_paging_widget.dart
Labels: type : bug, @0.6.0

#84 [#34][#35] [UI][Integrate] Thumbs up answer
  lib/screens/surveydetails/widget/question_paging_widget.dart
Labels: type : feature, @0.7.0

#85 [#29][#30] [UI][Integrate] Smiley answer
  lib/screens/surveydetails/widget/answer_smiley_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
Labels: type : feature, @0.7.0

#88 [#22] [Integrate] As a user, I can see the intro question when taking a survey
  lib/screens/surveydetails/widget/answer_intro_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
Labels: type : feature, @0.6.0

#90 [Release] 0.6.0
  .github/CODEOWNERS
  android/gradle.properties
  lib/api/repository/survey_repository.dart
  lib/api/service/survey_service.dart
  lib/model/response/answer_response.dart
  lib/model/response/question_response.dart
  lib/model/response/survey_detail_response.dart
  lib/model/ui/answer_ui_model.dart
  lib/model/ui/question_ui_model.dart
  lib/model/ui/survey_detail_ui_model.dart
  lib/model/ui/survey_ui_model.dart
  lib/resources/dimensions.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_state.dart
  lib/screens/home/home_view_model.dart
  lib/screens/home/widget/home_paging_widget.dart
  lib/screens/surveydetails/survey_detail_screen.dart
  lib/screens/surveydetails/survey_detail_state.dart
  lib/screens/surveydetails/survey_detail_view_model.dart
  lib/screens/surveydetails/survey_details_screen.dart
  lib/screens/surveydetails/widget/answer_intro_widget.dart
  lib/screens/surveydetails/widget/answer_rating_widget.dart
  lib/screens/surveydetails/widget/answer_smiley_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/usecases/get_survey_detail_use_case.dart
  lib/utils/app_navigator.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/usecases/get_survey_detail_use_case_test.dart
  test/viewmodels/home_view_model_test.dart
Labels: type : release, @0.6.0

#89 [#35] [#36] [UI] [Integrate] As a user, I can see the text field question when taking a survey
  lib/screens/surveydetails/survey_detail_screen.dart
  lib/screens/surveydetails/widget/answer_text_field_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/screens/widgets/background_widget.dart
Labels: type : feature, @0.7.0

#92 [Chore] Bump version to 0.7.0 for development
  pubspec.yaml
Labels: type: chore

#93 [#27] [#28] [UI] [Integrate] As a user, I can see the NPS question when taking a survey
  lib/l10n/app_en.arb
  lib/resources/dimensions.dart
  lib/screens/surveydetails/widget/answer_nps_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/theme/app_theme.dart
Labels: type : feature, @0.7.0

#94 [#25] [#26] [UI] [Integrate] Multi choice question
  lib/screens/surveydetails/widget/answer_multi_choice_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/theme/app_theme.dart
Labels: type : feature, @0.7.0

#91 [#37] [#38] [UI] [Integrate] As a user, I can see the text area question when taking a survey
  lib/screens/surveydetails/widget/answer_text_area_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/screens/widgets/app_input_widget.dart
Labels: type : feature, @0.7.0

#100 [Chore] Refactor answer widget ui
  lib/screens/surveydetails/widget/answer_multi_choice_widget.dart
  lib/screens/surveydetails/widget/answer_rating_widget.dart
  lib/screens/surveydetails/widget/answer_smiley_widget.dart
  lib/screens/surveydetails/widget/answer_text_area_widget.dart
  lib/screens/surveydetails/widget/answer_text_field_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
Labels: type: chore, @0.7.0

#96 [#95] [Chore] Update the background widget to blur the background on survey detail screen
  lib/screens/surveydetails/survey_detail_screen.dart
  lib/screens/widgets/background_widget.dart
Labels: type: chore, @0.7.0

#101 [#26] Single selection
  lib/model/response/question_response.dart
  lib/model/ui/question_ui_model.dart
  lib/screens/surveydetails/widget/answer_multi_choice_widget.dart
Labels: type : feature, @0.7.0

#99 [#23] [#24] [UI] [Integrate] Dropdown answer
  lib/resources/dimensions.dart
  lib/screens/surveydetails/widget/answer_dropdown_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, @0.7.0

#102 [#13] [UI] As a user, I can see the splash screen
  lib/screens/login/login_screen.dart
  lib/screens/widgets/background_widget.dart
Labels: type : feature, @0.7.0

#103 [Release] 0.7.0
  lib/l10n/app_en.arb
  lib/model/response/question_response.dart
  lib/model/ui/question_ui_model.dart
  lib/resources/dimensions.dart
  lib/screens/login/login_screen.dart
  lib/screens/surveydetails/survey_detail_screen.dart
  lib/screens/surveydetails/widget/answer_dropdown_widget.dart
  lib/screens/surveydetails/widget/answer_multi_choice_widget.dart
  lib/screens/surveydetails/widget/answer_nps_widget.dart
  lib/screens/surveydetails/widget/answer_rating_widget.dart
  lib/screens/surveydetails/widget/answer_smiley_widget.dart
  lib/screens/surveydetails/widget/answer_text_area_widget.dart
  lib/screens/surveydetails/widget/answer_text_field_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/screens/widgets/app_input_widget.dart
  lib/screens/widgets/background_widget.dart
  lib/theme/app_theme.dart
  pubspec.lock
  pubspec.yaml
Labels: type : release, @0.7.0

#104 [Chore] Bump version to 1.0.0 for development
  pubspec.yaml
Labels: type: chore, @1.0.0

#105 [#97] [Backend] As a user, I can fetch surveys with pagination
  lib/api/repository/survey_repository.dart
  lib/api/service/survey_service.dart
  lib/model/response/surveys_meta_response.dart
  lib/model/response/surveys_response.dart
  lib/screens/home/home_view_model.dart
  lib/usecases/get_surveys_use_case.dart
  test/usecases/get_surveys_use_case_test.dart
  test/viewmodels/home_view_model_test.dart
Labels: type : feature, @1.0.0

#106 [#98] [Integrate] As a user, I can fetch surveys with pagination
  lib/model/ui/survey_meta_model.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_view_model.dart
  lib/screens/home/widget/home_paging_widget.dart
Labels: type : feature, @1.0.0

#107 [#39] [UI] Thank you screen
  assets/images/ic_complete_survey.json
  lib/l10n/app_en.arb
  lib/resources/dimensions.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/screens/thankyou/thank_you_screen.dart
  lib/utils/app_navigator.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, @1.0.0

#109 [#40] [Backend] As a user, I can submit a survey
  lib/api/repository/survey_repository.dart
  lib/api/service/survey_service.dart
  lib/model/request/answer_request.dart
  lib/model/request/question_request.dart
  lib/model/request/submit_survey_request.dart
  lib/usecases/submit_survey_use_case.dart
  test/mocks/generate_mocks.dart
  test/usecases/submit_survey_use_case_test.dart
Labels: type : feature, @1.0.0

#113 [#112] Fix text width to limit to 60 percent of screen
  lib/screens/surveydetails/widget/answer_multi_choice_widget.dart
Labels: type : bug, @1.0.0

#114 [#111] Add heart emoji question
  lib/screens/surveydetails/widget/question_paging_widget.dart
Labels: @1.0.0

#108 [#51] Set up iOS distribution
  .github/workflows/ios_deploy_production_firebase.yml
  .github/workflows/ios_deploy_production_testflight.yml
  .github/workflows/ios_deploy_staging_testflight.yml
  .github/workflows/ios_deploy_to_testflight.yml
  .github/workflows/unit_test.yml
  ios/Flutter/AppFrameworkInfo.plist
  ios/Gemfile
  ios/Gemfile.lock
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/Info.plist
  ios/fastlane/Constants/Constants.rb
  ios/fastlane/Constants/Environments.rb
  ios/fastlane/Fastfile
  ios/fastlane/Gymfile
  ios/fastlane/Matchfile
  pubspec.lock
  pubspec.yaml
Labels: type: chore

#115 [#51] iOS distribution
  .github/workflows/ios_deploy_production_testflight.yml
  ios/Runner.xcodeproj/project.pbxproj
Labels: type: chore, @1.0.0

#116 Release/1.0.0
  .github/workflows/ios_deploy_production_firebase.yml
  .github/workflows/ios_deploy_production_testflight.yml
  .github/workflows/ios_deploy_staging_testflight.yml
  .github/workflows/ios_deploy_to_testflight.yml
  .github/workflows/unit_test.yml
  assets/images/ic_complete_survey.json
  ios/Flutter/AppFrameworkInfo.plist
  ios/Gemfile
  ios/Gemfile.lock
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/Info.plist
  ios/fastlane/Constants/Constants.rb
  ios/fastlane/Constants/Environments.rb
  ios/fastlane/Fastfile
  ios/fastlane/Gymfile
  ios/fastlane/Matchfile
  lib/api/repository/survey_repository.dart
  lib/api/service/survey_service.dart
  lib/l10n/app_en.arb
  lib/model/request/answer_request.dart
  lib/model/request/question_request.dart
  lib/model/request/submit_survey_request.dart
  lib/model/response/surveys_meta_response.dart
  lib/model/response/surveys_response.dart
  lib/model/ui/answer_ui_model.dart
  lib/model/ui/survey_meta_model.dart
  lib/resources/dimensions.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_view_model.dart
  lib/screens/home/widget/home_paging_widget.dart
  lib/screens/surveydetails/survey_detail_screen.dart
  lib/screens/surveydetails/survey_detail_state.dart
  lib/screens/surveydetails/survey_detail_view_model.dart
  lib/screens/surveydetails/widget/answer_dropdown_widget.dart
  lib/screens/surveydetails/widget/answer_multi_choice_widget.dart
  lib/screens/surveydetails/widget/answer_nps_widget.dart
  lib/screens/surveydetails/widget/answer_rating_widget.dart
  lib/screens/surveydetails/widget/answer_smiley_widget.dart
  lib/screens/surveydetails/widget/answer_text_area_widget.dart
  lib/screens/surveydetails/widget/answer_text_field_widget.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/screens/thankyou/thank_you_screen.dart
  lib/screens/widgets/rounded_rectangle_button_widget.dart
  lib/usecases/get_surveys_use_case.dart
  lib/usecases/submit_survey_use_case.dart
  lib/utils/app_navigator.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/usecases/get_surveys_use_case_test.dart
  test/usecases/submit_survey_use_case_test.dart
  test/viewmodels/home_view_model_test.dart
Labels: type : release, @1.0.0

#118 Release/1.0.0
  .github/workflows/ios_deploy_production_firebase.yml
  ios/fastlane/Fastfile
Labels: type : release, @1.0.0

#119 Merge main to develop
  .github/workflows/ios_deploy_production_firebase.yml
  ios/fastlane/Fastfile
Labels: type: chore, @1.0.0
