Repository nimblehq/flutter-ic-lydia-ryan, pull requests merged in 2023-04, with the labels that each got.

#54 [#7][UI] Login screen
  .github/workflows/test.yml
  .gitignore
  README.md
  assets/fonts/neuzeit.otf
  assets/fonts/neuzeit_bold.otf
  assets/fonts/neuzeit_regular.otf
  assets/images/2.0x/bg_login.png
  assets/images/3.0x/bg_login.png
  assets/images/bg_login.png
  assets/images/nimble_logo.png
  assets/images/nimble_logo_white.svg
  ios/Podfile.lock
  lib/l10n/app_en.arb
  lib/main.dart
  lib/resources/dimensions.dart
  lib/screens/login/login_keys.dart
  lib/screens/login/login_screen.dart
  lib/screens/widgets/login_input_widget.dart
  lib/screens/widgets/rounded_rectangle_button_widget.dart
  lib/theme/app_theme.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature

#53 [#8] [Backend] As a user, I can login with email and password
  lib/api/repository/auth_repository.dart
  lib/api/service/auth_service.dart
  lib/constants.dart
  lib/di/injection.dart
  lib/di/module/service_module.dart
  lib/di/provider/dio_provider.dart
  lib/env.dart
  lib/model/request/login_request.dart
  lib/model/response/converter/response_converter.dart
  lib/model/response/login_response.dart
  lib/usecases/login_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/auth_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
Labels: type : feature, @0.2.0

#56 Release/0.2.0
  .github/workflows/test.yml
  .gitignore
  README.md
  assets/fonts/neuzeit.otf
  assets/fonts/neuzeit_bold.otf
  assets/fonts/neuzeit_regular.otf
  assets/images/2.0x/bg_login.png
  assets/images/3.0x/bg_login.png
  assets/images/bg_login.png
  assets/images/nimble_logo.png
  assets/images/nimble_logo_white.svg
  ios/Podfile.lock
  lib/api/repository/auth_repository.dart
  lib/api/service/auth_service.dart
  lib/constants.dart
  lib/di/injection.dart
  lib/di/module/service_module.dart
  lib/di/provider/dio_provider.dart
  lib/env.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/model/request/login_request.dart
  lib/model/response/converter/response_converter.dart
  lib/model/response/login_response.dart
  lib/resources/dimensions.dart
  lib/screens/login/login_keys.dart
  lib/screens/login/login_screen.dart
  lib/screens/widgets/login_input_widget.dart
  lib/screens/widgets/rounded_rectangle_button_widget.dart
  lib/theme/app_theme.dart
  lib/usecases/login_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/auth_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
Labels: type : release, @0.2.0

#58 [#57] Update android deployment workflow flutter version
  .github/workflows/android_deploy_firebase.yml
  pubspec.yaml
Labels: type : bug, priority : high

#59 Release/0.2.1
  .github/workflows/android_deploy_firebase.yml
  pubspec.yaml
Labels: type : release, @0.2.1

#60 [Chore] Bring `0.2.1` to develop
  .github/workflows/android_deploy_firebase.yml
  pubspec.yaml
Labels: type: chore, @0.3.0

#63 [#62] Fix: Login JSON response cannot be parsed
  lib/model/response/login_response.dart
  test/api/repository/auth_repository_test.dart
  test/usecases/login_use_case_test.dart
Labels: type : bug, priority : high, @0.3.0

#64 Release/0.3.0
  lib/model/response/login_response.dart
  test/api/repository/auth_repository_test.dart
  test/usecases/login_use_case_test.dart
Labels: type : release, @0.3.0

#55 [#14] [UI] As a user, I can see the survey loading screen
  integration_test/my_home_page_test.dart
  lib/main.dart
  lib/resources/dimensions.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/widget/home_loading_widget.dart
  lib/theme/app_theme.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, @0.2.0, @0.3.0, @0.4.0

#61 [#9] [Integrate] login screen
  .github/workflows/android_deploy_firebase.yml
  .github/workflows/test.yml
  ios/Podfile.lock
  lib/api/service/auth_service.dart
  lib/base/base_view_model_state.dart
  lib/main.dart
  lib/screens/login/login_screen.dart
  lib/screens/login/login_view_model.dart
  lib/screens/widgets/app_input_widget.dart
  lib/screens/widgets/circle_loading_indicator.dart
  lib/usecases/base/base_use_case.dart
  lib/usecases/base/use_case_result.dart
  lib/usecases/login_use_case.dart
  lib/utils/toast_message.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
  test/viewmodels/login_view_model_test.dart
Labels: type : feature

#65 [#43][Integrate][Part1] Automatically signing in
  lib/di/module/storage_module.dart
  lib/screens/login/login_screen.dart
  lib/screens/login/login_view_model.dart
  lib/storage/shared_preferences_utils.dart
  lib/usecases/login_use_case.dart
  lib/usecases/verify_logged_in_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
  test/usecases/verify_login_use_case_test.dart
  test/viewmodels/login_view_model_test.dart
Labels: type : feature

#67 [#66][Backend] As a user, I can automatically login
  lib/api/repository/auth_repository.dart
  lib/api/service/auth_service.dart
  lib/constants.dart
  lib/model/request/refresh_token_request.dart
  lib/usecases/refresh_token_use_case.dart
  test/usecases/refresh_token_use_case_test.dart
Labels: type : feature

#68 [#43][Part2][Integrate] Automatically signing in when API returns 401
  lib/di/interceptor/app_interceptor.dart
  lib/di/provider/dio_provider.dart
  lib/storage/shared_preferences_utils.dart
  lib/usecases/login_use_case.dart
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
Labels: type : feature

#71 [#16] Backend for getting survey list
  lib/api/repository/survey_repository.dart
  lib/api/service/survey_service.dart
  lib/di/module/service_module.dart
  lib/di/provider/dio_provider.dart
  lib/main.dart
  lib/model/response/converter/response_converter.dart
  lib/model/response/login_response.dart
  lib/model/response/survey_response.dart
  lib/model/response/surveys_response.dart
  lib/usecases/get_surveys_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/usecases/get_surveys_use_case_test.dart
  test/viewmodels/login_view_model_test.dart
Labels: type : feature

#74 [Chore] bump version to 0.5.0
  pubspec.yaml
Labels: type: chore, @0.5.0

#76 [Chore] Update Github code owners
  .github/CODEOWNERS
Labels: type: chore

#75 [#18][Part1] [UI] Survey Details screen
  lib/main.dart
  lib/screens/login/login_screen.dart
  lib/screens/login/login_view_model.dart
  lib/screens/surveydetails/survey_details_screen.dart
  lib/storage/shared_preferences_utils.dart
  lib/usecases/verify_logged_in_use_case.dart
  lib/utils/app_navigator.dart
  test/mocks/generate_mocks.dart
  test/usecases/verify_login_use_case_test.dart
  test/viewmodels/login_view_model_test.dart
Labels: type : feature

#77 [#18][#21][Part2] [UI] Survey Details screen
  assets/images/ic_back.svg
  lib/l10n/app_en.arb
  lib/model/ui/question_ui_model.dart
  lib/resources/dimensions.dart
  lib/screens/home/widget/home_paging_widget.dart
  lib/screens/login/login_screen.dart
  lib/screens/surveydetails/survey_details_screen.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/screens/widgets/rounded_rectangle_button_widget.dart
Labels: type : feature

#78 Release/0.5.0
  .github/CODEOWNERS
  assets/images/ic_back.svg
  lib/extension/date_time_extension.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/model/ui/question_ui_model.dart
  lib/model/ui/survey_ui_model.dart
  lib/resources/dimensions.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/widget/home_paging_widget.dart
  lib/screens/login/login_screen.dart
  lib/screens/login/login_view_model.dart
  lib/screens/surveydetails/survey_details_screen.dart
  lib/screens/surveydetails/widget/question_paging_widget.dart
  lib/screens/widgets/background_widget.dart
  lib/screens/widgets/rounded_rectangle_button_widget.dart
  lib/storage/shared_preferences_utils.dart
  lib/usecases/verify_logged_in_use_case.dart
  lib/utils/app_navigator.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/usecases/verify_login_use_case_test.dart
  test/viewmodels/login_view_model_test.dart
Labels: type : release
